// Objeto contendo as descrições de dano por tipo e valor (d20)
export const damageDescriptions = {
    'contusão': {
        1: 'Você chama isso de <strong>crítico</strong>? Role seus dados de dano normais.',
        '2-3': '<strong>Perdeu o balanço!</strong> Role seus dados de dano normais e o próximo ataque contra a criatura tem <strong>vantagem</strong>.',
        '4-6': '<strong>Bom golpe!</strong> Não role seus dados de dano; em vez disso, use o resultado <strong>máximo possível</strong> com esses dados.',
        '7-8': '<strong>Arremetida cambaleante!</strong> Não role seus dados de dano; em vez disso, trate o resultado <strong>máximo possível</strong> com esses dados e empurre a criatura até 4,5 metros em qualquer direção.',
        '9-11': '<strong>Grande golpe!</strong> Role seus dados de dano <strong>duas vezes</strong> e aplique-os juntos.',
        '12-13': '<strong>Sente-se!</strong> Role os dados de dano <strong>duas vezes</strong> e aplique-os juntos e a criatura é <strong>derrubada</strong>.',
        '14-16': '<strong>Balançado e rolado!</strong> Role os dados de dano <strong>duas vezes</strong> e aplique-os juntos, empurre a criatura até 4,5 metros de distância, e a criatura é <strong>derrubada</strong>.',
        '17-18': '<strong>Lesão grave!</strong> Cause a quantidade <strong>máxima</strong> de dano de seus dados de dano normais, em seguida, role seus dados de dano e adicione ao resultado. Em seguida, role na tabela de <strong>lesões menores</strong>. Se a criatura estiver usando uma armadura pesada role na tabela de <strong>lesões maiores</strong>, em vez disso.',
        19: '<strong>Esmagado!</strong> Considere o resultado <strong>máximo</strong> de seus dados de dano <strong>duas vezes</strong> e role na tabela de <strong>lesões maiores</strong>.',
        20: '<strong>Espalhado!</strong> Considere o resultado <strong>máximo</strong> de seus dados de dano <strong>duas vezes</strong>, a criatura fica <strong>atordoada</strong> até o final do próximo turno e role na tabela de <strong>lesões maiores</strong>.'
    },
    'perfurante': {
        1: 'Você chama isso de <strong>crítico</strong>? Role seus dados de dano normais.',
        '2-3': '<strong>Invista e estoque!</strong> Role seus dados de dano <strong>duas vezes</strong> e use o resultado <strong>mais alto</strong>.',
        '4-6': '<strong>Bom golpe!</strong> Não role seus dados de dano; em vez disso, use o resultado <strong>máximo possível</strong> com esses dados.',
        '7-8': '<strong>Perfurado!</strong> Role seus dados de dano <strong>duas vezes</strong> e aplique-os juntos.',
        '9-11': '<strong>Grande golpe!</strong> Role seus dados de dano <strong>duas vezes</strong> e aplique-os juntos.',
        '12-13': '<strong>Queijo suíço!</strong> Role o <strong>dobro</strong> de dados de dano como normal. Em seguida, role <strong>duas vezes</strong> na tabela de <strong>lesões menores</strong> e use o <strong>menor resultado</strong>.',
        '14-16': '<strong>Cheio de furos!</strong> Role seus dados de dano <strong>duas vezes</strong> e aplique-os juntos e role na tabela de <strong>lesões menores</strong>.',
        '17-18': '<strong>Alfinetada cruel!</strong> Role seus dados de dano <strong>duas vezes</strong> e aplique-os juntos e role a tabela de <strong>lesões maiores</strong>.',
        19: '<strong>Espetada completa!</strong> Considere o resultado <strong>máximo</strong> de seus dados de dano <strong>duas vezes</strong> e role na tabela de <strong>lesões maiores</strong>.',
        20: '<strong>Atravessado!</strong> Considere o resultado <strong>máximo</strong> de seus dados de dano <strong>duas vezes</strong>, role na tabela de <strong>lesões menores</strong> e role na tabela de <strong>lesões maiores</strong>.'
    },
    'cortante': {
        1: 'Você chama isso de <strong>crítico</strong>? Role seus dados de dano normais.',
        '2-3': '<strong>Cortado e fatiado em cubos!</strong> Role seus dados de dano normais e a criatura perde <strong>1d6 pontos de vida</strong> no início do próximo turno.',
        '4-6': '<strong>Bom golpe!</strong> Não role seus dados de dano, em vez disso, considere o resultado <strong>máximo possível</strong> com esses dados.',
        '7-8': '<strong>Abriu o corte!</strong> Role seus dados de dano normalmente e a criatura está <strong>sangrando</strong>. Durante o próximo minuto, a criatura perde <strong>1d4 de dano</strong> no início de cada um de seus turnos até usar uma ação para curar esta ferida.',
        '9-11': '<strong>Grande golpe!</strong> Role seus dados de dano <strong>duas vezes</strong> e aplique-os juntos.',
        '12-13': '<strong>Fatia profunda!</strong> Role seus dados de dano <strong>duas vezes</strong> e aplique-os juntos e a criatura está <strong>sangrando</strong>. Durante o próximo minuto, a criatura perde <strong>1d8 pontos de vida</strong> no início de cada um de seus turnos até usar uma ação para curar esta ferida.',
        '14-16': '<strong>Lacerado!</strong> Role seus dados de dano <strong>duas vezes</strong> e adicione-os juntos e a criatura está <strong>sangrando</strong>. Para o próximo minuto, a criatura perde <strong>1d12 pontos de vida</strong> no início de cada um de seus turnos até usar uma ação para curar esta ferida.',
        '17-18': '<strong>Fendido!</strong> Considere a quantidade <strong>máxima</strong> de dano de seus dados de dano normais, em seguida, role seus dados de dano e adicione ao resultado. Então, role na tabela de <strong>lesões menores</strong>. Se a criatura estiver usando armadura leve ou nenhuma role na tabela de <strong>lesões maiores</strong>, em vez disso.',
        19: '<strong>Dissecado!</strong> Considere o resultado <strong>máximo</strong> de seus dados de dano <strong>duas vezes</strong> e role na tabela de <strong>lesões maiores</strong>.',
        20: '<strong>Talhado!</strong> Considere o resultado <strong>máximo</strong> de seus dados de dano <strong>duas vezes</strong>, role na tabela de <strong>lesões maiores</strong> e a criatura está <strong>sangrando</strong>. Durante o próximo minuto, a criatura perde <strong>2d8 pontos de vida</strong> no início de cada um de seus turnos até usar uma ação para curar esta ferida.'
    },
    'radiante': {
        1: 'Você chama isso de <strong>crítico</strong>? Role seus dados de dano normais.',
        '2-3': '<strong>Confuso!</strong> Role seus dados de dano normais e a criatura não pode se aproximar de você até o final do próximo turno.',
        '4-6': '<strong>Bom acerto!</strong> Não role seus dados de dano, em vez disso, considere o resultado <strong>máximo possível</strong> com esses dados.',
        '7-8': '<strong>Explosão abatedora!</strong> Role seus dados de dano normais e a criatura está <strong>amedrontada</strong> até o final do seu próximo turno.',
        '9-11': '<strong>Grande acerto!</strong> Role o <strong>dobro</strong> de seus dados de dano normais.',
        '12-13': '<strong>Admirado!</strong> Role o <strong>dobro</strong> de seus dados de dano normais e a criatura fica <strong>amedrontada</strong> até o final do seu próximo turno.',
        '14-16': '<strong>Terror sagrado!</strong> Role o <strong>dobro</strong> de seus dados de dano normais e role na tabela de <strong>lesões menores</strong>. Além disso, a criatura é <strong>amedrontada</strong> pelo próximo minuto. Ela pode fazer um teste de resistência de Sabedoria (CD 16) no final de cada um de seus turnos para encerrar esse efeito.',
        '17-18': '<strong>Marca da justiça!</strong> Considere a quantidade <strong>máxima</strong> de dano para seus dados de dano normais, em seguida, role seu dado de dano e adicione ao resultado, então role na tabela de <strong>lesões menores</strong>. Além disso, a criatura <strong>brilha</strong> pelo próximo minuto. Ao <strong>brilhar</strong>, ela produz luz plena até 3 metros e penumbra até 9 metros e todos os ataques bem sucedidos contra a criatura causa um dano radiante adicional de <strong>1d4</strong>.',
        19: '<strong>Ira dos deuses!</strong> Considere o resultado <strong>máximo</strong> de seus dados de dano <strong>duas vezes</strong> e role na tabela de <strong>lesões maiores</strong>.',
        20: '<strong>Punição!</strong> Considere o resultado <strong>máximo</strong> de seus dados de dano <strong>duas vezes</strong> e role na tabela de <strong>lesões maiores</strong>. Além disso, a criatura <strong>brilha</strong> pelo próximo minuto. Ao <strong>brilhar</strong>, ela produz luz plena até 3 metros e penumbra até 9 metros, e todos os ataques bem sucedidos contra a criatura, causa um dano radiante adicional de <strong>1d6</strong>.'
    },
    'ácido': {
        1: 'Você chama isso de <strong>crítico</strong>? Role seus dados de dano normais.',
        '2-3': '<strong>Bilis escaldante!</strong> Role seus dados de dano normais e a criatura fica com <strong>cicatrizes</strong>. Enquanto tiver uma <strong>cicatriz</strong>, a criatura tem <strong>desvantagem</strong> em todos os testes de habilidade de Carisma, exceto Carisma (Intimidação). A <strong>cicatriz</strong> pode ser reparada da mesma forma que uma <strong>lesão menor</strong>.',
        '4-6': '<strong>Bom acerto!</strong> Não role seus dados de dano, em vez disso, trate o resultado <strong>máximo possível</strong> com esses dados.',
        '7-8': '<strong>Carne derretida!</strong> Role seus dados de dano normais e a criatura é <strong>desfigurada</strong>. Enquanto <strong>desfigurada</strong>, a criatura tem <strong>desvantagem</strong> em todos os testes de habilidade de Carisma, exceto Carisma (Intimidação). A <strong>desfiguração</strong> pode ser reparada pela magia <strong>restauração maior</strong>.',
        '9-11': '<strong>Grande acerto!</strong> Role seus dados de dano <strong>duas vezes</strong> e adicione-os juntos.',
        '12-13': '<strong>Carne fervendo!</strong> Role o <strong>dobro</strong> de seus dados de dano normais e se a criatura estiver usando armaduras, seu modificador de CA é reduzido em <strong>1</strong> até que ela possa ser reparada (por 1/4 do preço de nova armadura do mesmo tipo) ou purificada (se a armadura for mágica). Se a criatura não estiver usando armadura, role na tabela de <strong>lesões menores</strong>.',
        '14-16': '<strong>Mutilação Horrível!</strong> Role o <strong>dobro</strong> de seus dados de dano normais e role na tabela de <strong>lesões menores</strong>. Além disso, a criatura está <strong>desfigurada</strong>. Enquanto <strong>desfigurada</strong>, a criatura tem <strong>desvantagem</strong> em todos os testes de habilidade de Carisma, exceto Carisma (Intimidação). A <strong>desfiguração</strong> pode ser reparada pela magia <strong>restauração maior</strong>.',
        '17-18': '<strong>Trauma cáustico!</strong> Considere a quantidade <strong>máxima</strong> de dano de seus dados de dano normais, em seguida, role seus dados de dano e adicione esse resultado. Se a criatura estiver usando armaduras, role na tabela de <strong>lesões menores</strong> e seu modificador de CA é reduzido em <strong>2</strong> até que ela possa ser reparada (por metade do preço de armadura nova do mesmo tipo) ou limpa (se a armadura for mágica). Se a criatura não estiver vestindo armadura, role na tabela de <strong>lesões maiores</strong>.',
        19: '<strong>Vitrificado!</strong> Considere o resultado <strong>máximo</strong> de seus dados de dano <strong>duas vezes</strong> e role na tabela de <strong>lesões maiores</strong>.',
        20: '<strong>Banho ácido!</strong> Considere o resultado <strong>máximo</strong> de seus dados de dano <strong>duas vezes</strong>. Se a criatura estiver usando armaduras, a armadura é <strong>destruída</strong> (se não mágica) ou <strong>inutilizada</strong> até ser limpa durante um descanso longo (se mágico) e role na tabela de <strong>lesões maiores</strong>. Se a criatura não estiver usando armadura, role na tabela de <strong>lesões maiores</strong> e a criatura está <strong>desfigurada</strong>. Enquanto <strong>desfigurada</strong>, a criatura tem <strong>desvantagem</strong> em todos os testes de habilidade de Carisma, exceto Carisma (Intimidação). A <strong>desfiguração</strong> pode ser reparada pela magia <strong>restauração maior</strong>.'
    },
    'fogo': {
        1: 'Você chama isso de <strong>crítico</strong>? Role seus dados de dano normais.',
        '2-3': '<strong>Onda de calor!</strong> Role seus dados de dano normais e os testes de ataque para ataques que causam dano de fogo têm <strong>vantagem</strong> quando feitos contra a criatura até o final do próximo turno.',
        '4-6': '<strong>Bom acerto!</strong> Não role seus dados de dano, em vez disso, considere o resultado como sendo o <strong>máximo possível</strong> com esses dados.',
        '7-8': '<strong>Lampejo quente!</strong> Role seus dados de dano normais e a criatura está em <strong>chamas</strong>. Enquanto a criatura está em <strong>chamas</strong>, ela sofre <strong>2d4</strong> de dano de fogo no início de cada um de seus turnos. A criatura pode encerrar esta condição se jogando ao chão e usando 1,5 metros de deslocamento para rolar.',
        '9-11': '<strong>Grande acerto!</strong> Role o <strong>dobro</strong> de seus dados de dano normais.',
        '12-13': '<strong>Em chamas!</strong> Role o <strong>dobro</strong> de seus dados de dano normais e a criatura está em <strong>chamas</strong>. Enquanto a criatura está em <strong>chamas</strong>, ela sofre <strong>2d6</strong> de dano de fogo no início de cada um de seus turnos. A criatura pode encerrar esta condição se jogando ao chão e usando 1,5 metros de deslocamento para rolar.',
        '14-16': '<strong>Queimado vivo!</strong> Role o <strong>dobro</strong> de seus dados de dano normais e a criatura está <strong>carbonizada</strong>. Se a criatura tiver resistência a fogo, ela perde essa resistência. Se a criatura não tiver resistência ao fogo, ganha <strong>vulnerabilidade</strong> ao fogo. Ambos os efeitos podem ser encerrados da mesma forma que uma <strong>lesão menor</strong>.',
        '17-18': '<strong>Fogo do inferno!</strong> Considere a quantidade <strong>máxima</strong> de dano de seus dados de dano normais, em seguida, role seus dados de dano e adicione ao resultado, e então, role na tabela de <strong>lesões menores</strong>. Além disso, a criatura está em <strong>chamas</strong>. Ela sofre <strong>2d6</strong> de dano de fogo no início de cada um de seus turnos. A criatura pode encerrar esta condição se jogando ao chão e usando 1,5 metros de deslocamento para rolar.',
        19: '<strong>Combustão!</strong> Considere o resultado <strong>máximo</strong> de seus dados de dano <strong>duas vezes</strong> e role na tabela de <strong>lesão maior</strong>.',
        20: '<strong>Inferno!</strong> Considere o resultado <strong>máximo</strong> de seus dados de dano <strong>duas vezes</strong> e role na tabela de <strong>lesão maior</strong>. Além disso, a criatura está em <strong>chamas</strong>. Ela sofre <strong>2d8</strong> de dano de fogo no início de cada um de seus turnos. A criatura pode encerrar esta condição se jogando ao chão e usando 1,5 metros de deslocamento para rolar.'
    },
    'gelo': {
        1: 'Você chama isso de <strong>crítico</strong>? Role seus dados de dano normais.',
        '2-3': '<strong>Calafrios!</strong> Role seus dados de dano normais e a criatura só pode se mover a <strong>metade do seu deslocamento</strong> no próximo turno.',
        '4-6': '<strong>Bom acerto!</strong> Não role seus dados de dano, em vez disso, trate o resultado como o <strong>máximo possível</strong> com esses dados.',
        '7-8': '<strong>Gelado!</strong> Role seus dados de dano normais e o <strong>deslocamento</strong> da criatura é <strong>0</strong> até o final do próximo turno.',
        '9-11': '<strong>Grande acerto!</strong> Role o <strong>dobro</strong> de seus dados de dano normais.',
        '12-13': '<strong>Congelando!</strong> Role o <strong>dobro</strong> de seus dados de dano normais e a criatura está <strong>paralisada</strong> até o final do próximo turno.',
        '14-16': '<strong>Congelado!</strong> Role o <strong>dobro</strong> de seus dados de dano normais e a criatura está <strong>paralisada</strong> até o final do próximo turno. Se a criatura sofrer dano antes do final do seu próximo turno, role na tabela de <strong>lesões menores</strong>.',
        '17-18': '<strong>Bloco de gelo!</strong> Considere a quantidade <strong>máxima</strong> de dano de seus dados de dano normais, em seguida, role seus dados de dano e adicione esse resultado. A criatura está <strong>paralisada</strong> até o final do próximo turno e role na tabela de <strong>lesões menores</strong>.',
        19: '<strong>Glacial!</strong> Considere o resultado <strong>máximo</strong> de seus dados de dano <strong>duas vezes</strong> e role na tabela de <strong>lesões maiores</strong>.',
        20: '<strong>Abaixo de zero!</strong> Considere o resultado <strong>máximo</strong> de seus dados de dano <strong>duas vezes</strong>, role na tabela de <strong>lesões maiores</strong> e a criatura está <strong>paralisada</strong> no próximo minuto. A criatura pode realizar um teste de resistência de Constituição no final de cada um de seus turnos (CD 16) para encerrar esse efeito. Se ele falhar nesse teste três vezes, ele fica <strong>petrificado</strong>, embora o efeito seja <strong>congelado</strong> em um bloco de gelo.'
    },
    'venenoso': {
        1: 'Você chama isso de <strong>crítico</strong>? Role seus dados de dano normais.',
        '2-3': '<strong>Nauseabundo!</strong> Role seus dados de dano normais e a criatura tem <strong>desvantagem</strong> em seu próximo teste de habilidade, testes de ataque ou teste de resistência.',
        '4-6': '<strong>Bom acerto!</strong> Não role seus dados de dano, em vez disso, considere o resultado <strong>máximo possível</strong> com esses dados.',
        '7-8': '<strong>Enjoado!</strong> Role seus dados de dano normais e a criatura tem <strong>desvantagem</strong> em todos os testes de habilidade, testes de ataque e testes de resistência até o final do próximo turno.',
        '9-11': '<strong>Grande acerto!</strong> Role o <strong>dobro</strong> de seus dados de dano normais.',
        '12-13': '<strong>Envenenado!</strong> Role o <strong>dobro</strong> de seus dados de dano normais e a criatura está <strong>envenenada</strong> pelo próximo minuto. A criatura pode fazer um teste de resistência no final de cada um de seus turnos (CD 12) para encerrar esse efeito.',
        '14-16': '<strong>Contaminado!</strong> Role o <strong>dobro</strong> de seus dados de dano normais e a criatura está <strong>envenenada</strong> pelo próximo minuto. A criatura pode fazer um teste de resistência no final de cada um de seus turnos (CD 16) para encerrar esse efeito.',
        '17-18': '<strong>Choque tóxico!</strong> Considere a quantidade <strong>máxima</strong> de dano de seus dados de dano normais, em seguida, role seus dados de dano e adicione ao resultado. Então, role na tabela de <strong>lesões menores</strong> e a criatura está <strong>envenenada</strong> pelo próximo minuto. A criatura pode fazer um teste de resistência no final de cada um de seus turnos (CD 12) para encerrar esse efeito.',
        19: '<strong>Falha sistêmica!</strong> Considere o resultado <strong>máximo</strong> de seus dados de dano <strong>duas vezes</strong> e role na tabela de <strong>lesões maiores</strong>.',
        20: '<strong>Colapso biológico!</strong> Considere o resultado <strong>máximo</strong> de seus dados de dano <strong>duas vezes</strong>, role na tabela de <strong>lesões maiores</strong> e a criatura está <strong>envenenada</strong> pelo próximo minuto. A criatura pode fazer um teste de resistência no final de cada um de seus turnos (CD 16) para encerrar esse efeito.'
    },
    'necrótico': {
        1: 'Você chama isso de <strong>crítico</strong>? Role seus dados de dano normais.',
        '2-3': '<strong>Corrompido!</strong> Role seus dados de dano normais e a criatura não pode <strong>recuperar pontos de vida</strong> até o final do seu próximo turno.',
        '4-6': '<strong>Bom acerto!</strong> Não role seus dados de dano, em vez disso, considere o resultado <strong>máximo possível</strong> com esses dados.',
        '7-8': '<strong>Supurado!</strong> Role seus dados de dano normais e os <strong>pontos de vida máximos</strong> da criatura são <strong>reduzidos</strong> pelo mesmo valor.',
        '9-11': '<strong>Grande acerto!</strong> Role o <strong>dobro</strong> de seus dados de dano normais.',
        '12-13': '<strong>Decaído!</strong> Role o <strong>dobro</strong> de seus dados de dano normais e os <strong>pontos de vida máximos</strong> da criatura são <strong>reduzidos</strong> pela mesma quantidade.',
        '14-16': '<strong>Definhando!</strong> Role o <strong>dobro</strong> de seus dados de dano normais e a criatura não pode <strong>recuperar pontos de vida</strong> pelo próximo minuto. Ela pode fazer um teste de resistência de constituição (CD 16) no final de cada um de seus turnos para encerrar esse efeito.',
        '17-18': '<strong>Mirrado!</strong> Considere a quantidade <strong>máxima</strong> de dano de seus dados de dano normais, e em seguida, role seus dados de dano e adicione ao resultado. Os <strong>pontos de vida máximos</strong> da criatura são <strong>reduzidos</strong> pelo mesmo valor. Em seguida, role na tabela de <strong>lesões menores</strong>.',
        19: '<strong>Atrofiado!</strong> Considere o resultado <strong>máximo</strong> de seus dados de dano <strong>duas vezes</strong> e role na tabela de <strong>lesões maiores</strong>.',
        20: '<strong>Putrefato!</strong> Considere o resultado <strong>máximo</strong> de seus dados de dano <strong>duas vezes</strong>, os <strong>pontos de vida máximos</strong> da criatura são <strong>reduzidos</strong> pela mesma quantidade e a criatura não pode <strong>recuperar pontos de vida</strong> até o final do próximo turno. Em seguida, role na tabela de <strong>lesões maiores</strong>.'
    },
    'psíquico': {
        1: 'Você chama isso de <strong>crítico</strong>? Role seus dados de dano normais.',
        '2-3': '<strong>Desorientado!</strong> Role seus dados de dano normais e você <strong>controla o deslocamento</strong> da criatura no próximo turno.',
        '4-6': '<strong>Confuso!</strong> Role seus dados de dano normais e a criatura não pode <strong>diferenciar amigo de inimigo</strong> até o final do próximo turno.',
        '7-8': '<strong>Bom acerto!</strong> Não role seus dados de dano, em vez disso, considere o resultado <strong>máximo possível</strong> com esses dados.',
        '9-11': '<strong>Grande acerto!</strong> Role o <strong>dobro</strong> de seus dados de dano normais.',
        '12-13': '<strong>Dominado!</strong> Role o <strong>dobro</strong> de seus dados de dano normais e você <strong>controla a ação</strong> da criatura no próximo turno.',
        '14-16': '<strong>Fratura psicológica!</strong> Role o <strong>dobro</strong> de seus dados de dano normais e role na tabela de <strong>Insanidade</strong> com <strong>desvantagem</strong>.',
        '17-18': '<strong>Ruptura psicológica!</strong> Considere a quantidade <strong>máxima</strong> de dano de seus dados de dano normais, em seguida, role seus dados de dano e adicione ao resultado. Em seguida, role na tabela <strong>Insanidade</strong>.',
        19: '<strong>Loucura!</strong> Considere o resultado <strong>máximo</strong> de seus dados de dano <strong>duas vezes</strong> e role na tabela de <strong>Insanidade</strong>.',
        20: '<strong>Mente derretida!</strong> Considere o resultado <strong>máximo</strong> de seus dados de dano <strong>duas vezes</strong> e role na tabela de <strong>Insanidade</strong> com <strong>vantagem</strong>.'
    },
    'energia': {
        1: 'Você chama isso de <strong>crítico</strong>? Role seus dados de dano normais.',
        '2-3': '<strong>Choque mágico!</strong> Role seus dados de dano normais e a criatura tem <strong>desvantagem</strong> nos testes de resistência contra magias até o final do seu próximo turno.',
        '4-6': '<strong>Bom acerto!</strong> Não role seus dados de dano, em vez disso, considere o resultado <strong>máximo possível</strong> com eles.',
        '7-8': '<strong>Incandescência sobrenatural!</strong> Role seus dados de dano normais e testes de ataque com magia contra a criatura têm <strong>vantagem</strong> até o final do próximo turno.',
        '9-11': '<strong>Grande acerto!</strong> Role o <strong>dobro</strong> de seus dados de dano normais.',
        '12-13': '<strong>Golpe encantado!</strong> Role o <strong>dobro</strong> de seus dados de dano normais e a criatura fica <strong>enfeitiçada</strong> até o final do seu próximo turno. Enquanto está <strong>enfeitiçada</strong>, os testes de resistência contra magia são feitos com <strong>desvantagem</strong> e os testes de ataque com magia contra ele têm <strong>vantagem</strong>.',
        '14-16': '<strong>Magnetismo místico!</strong> Role o <strong>dobro</strong> de seus dados de dano normais e a criatura está <strong>enfeitiçada</strong> pelo próximo minuto. Enquanto está <strong>enfeitiçada</strong>, os testes de resistência contra magia são feitos com <strong>desvantagem</strong> e os testes de ataque com magia contra ele têm <strong>vantagem</strong>. No final de cada um dos turnos da criatura, ela pode fazer um teste de resistência de inteligência (CD 14) para encerrar o efeito.',
        '17-18': '<strong>Fascinado!</strong> Considere a quantidade <strong>máxima</strong> de dano de seus dados de dano normais, em seguida, role seus dados de dano e adicione ao resultado, e então role na tabela de <strong>lesões menores</strong>. Além disso, a criatura está <strong>enfeitiçada</strong> pelo próximo minuto. Enquanto está <strong>enfeitiçada</strong>, os testes de resistência contra magia são feitos com <strong>desvantagem</strong> e os testes de ataque com magia contra ele têm <strong>vantagem</strong>. No final de cada um dos turnos da criatura, ela pode fazer um teste de resistência de inteligência (CD 16) para encerrar o efeito.',
        19: '<strong>Injúria arcana!</strong> Considere o resultado <strong>máximo</strong> de seus dados de dano <strong>duas vezes</strong> e role na tabela de <strong>lesão maior</strong>.',
        20: '<strong>Magicamente espancado!</strong> Considere o resultado <strong>máximo</strong> de seus dados de dano <strong>duas vezes</strong> e role na tabela de <strong>lesão maior</strong>. Além disso, a criatura está <strong>encantada</strong> pelo próximo minuto. Enquanto está <strong>enfeitiçada</strong>, os testes de resistência contra magia são feitos com <strong>desvantagem</strong> e os testes de ataque com magia contra ele têm <strong>vantagem</strong>. No final de cada um dos turnos da criatura, ela pode fazer um teste de resistência de inteligência (CD 16) para encerrar o efeito.'
    },
    'elétrico': {
        1: 'Você chama isso de <strong>crítico</strong>? Role seus dados de dano normais.',
        '2-3': '<strong>Chocante!</strong> Role seus dados de dano normais e a criatura não pode usar <strong>reações</strong> até o final do seu próximo turno.',
        '4-6': '<strong>Bom acerto!</strong> Não role seus dados de dano, em vez disso, considere o resultado <strong>máximo possível</strong> com esses dados.',
        '7-8': '<strong>Fagulha voadora!</strong> Role seus dados de dano normais e você pode escolher outra criatura dentro de 4,5 metros do alvo. Essa criatura deve ser bem sucedida em um teste de resistência de Destreza (CD 14) ou sofrerá a <strong>metade do mesmo dano</strong>.',
        '9-11': '<strong>Grande acerto!</strong> Role o <strong>dobro</strong> de seus dados de dano normais.',
        '12-13': '<strong>Arco elétrico!</strong> Role o <strong>dobro</strong> de seus dados de dano normais e você pode escolher outra criatura dentro de 4,5 metros da vítima. Essa criatura deve ser bem sucedida em um teste de resistência de Destreza (CD 18) ou sofrerá a <strong>metade do mesmo dano</strong>.',
        '14-16': '<strong>Fulminado!</strong> Role o <strong>dobro</strong> de seus dados de dano normais e role na tabela de <strong>lesões menores</strong>. Se a criatura estiver usando uma armadura de metal role na tabela de <strong>lesões maiores</strong>.',
        '17-18': '<strong>Iluminado!</strong> Considere a quantidade <strong>máxima</strong> de dano de seus dados de dano normais, em seguida, role seus dados de dano e adicione ao resultado. A criatura e cada criatura que você escolher dentro de 4,5 metros dele não podem fazer <strong>reações</strong> até o final do próximo turno. Em seguida, role na tabela de <strong>lesões menores</strong>.',
        19: '<strong>Eletrocutado!</strong> Considere o resultado <strong>máximo</strong> de seus dados de dano <strong>duas vezes</strong> e role na tabela de <strong>lesões maiores</strong>.',
        20: '<strong>Punição elétrica!</strong> Considere o resultado <strong>máximo</strong> de seus dados de dano <strong>duas vezes</strong> e você pode escolher outra criatura dentro de 4,5 metros da vítima. Essa criatura deve ter sucesso em um teste de resistência de Destreza (CD 20) ou sofrerá a <strong>metade do dano</strong>. Em seguida, role na tabela de <strong>lesões maiores</strong>.'
    },
    'trovão': { // Mapeando 'trovão' para 'trovejante' do PDF
        1: 'Você chama isso de <strong>crítico</strong>? Role seus dados de dano normais.',
        '2-3': '<strong>Estrondo!</strong> Role seus dados de dano normais e a criatura fica <strong>ensurdecida</strong> até o final do próximo turno.',
        '4-6': '<strong>Bom acerto!</strong> Não role seus dados de dano, em vez disso, considere o resultado <strong>máximo possível</strong> com esses dados.',
        '7-8': '<strong>Cábum!</strong> Role seus dados de dano normais e a criatura fica <strong>surda</strong> por um minuto.',
        '9-11': '<strong>Grande acerto!</strong> Role o <strong>dobro</strong> de seus dados de dano normais.',
        '12-13': '<strong>Estrondo do trovão!</strong> Role o <strong>dobro</strong> de seus dados de dano normais e a criatura fica <strong>atordoada</strong> até o início do seu próximo turno e depois <strong>adormecida</strong> por um minuto.',
        '14-16': '<strong>Rompe tímpanos!</strong> Role o <strong>dobro</strong> de seus dados de dano normais e a criatura fica <strong>ensurdecida permanentemente</strong>. Em seguida, role na tabela de <strong>lesões menores</strong>.',
        '17-18': '<strong>Explosão contundente!</strong> Considere a quantidade <strong>máxima</strong> de dano de seus dados de dano normais, em seguida, role seus dados de dano e adicione esse resultado. A criatura fica <strong>atordoada</strong> até o final do seu próximo turno e <strong>ensurdecida permanentemente</strong>. Em seguida, role na tabela de <strong>lesões menores</strong>.',
        19: '<strong>Parede de som!</strong> Considere o resultado <strong>máximo</strong> de seus dados de dano <strong>duas vezes</strong> e role na tabela de <strong>lesões maiores</strong>.',
        20: '<strong>Reserva sônica!</strong> Considere o resultado <strong>máximo</strong> de seus dados de dano <strong>duas vezes</strong>, a criatura é <strong>ensurdecida permanentemente</strong> e <strong>atordoada</strong> até o final da próxima rodada. Em seguida, role na tabela de <strong>lesões maiores</strong>.'
    }
};
