export const failureDescriptions = {
    1: '<strong>Fora de Combate:</strong> Uma <strong>fatalidade</strong> acontece, <strong>morte súbita</strong>. Em Combate: Dá um <strong>AdO Vorpal</strong> ao adversário.',
    2: 'Acerta a si próprio com um <strong>golpe crítico</strong>, cai <strong>inconsciente</strong> por 1d6 minutos. Role na tabela <strong>Insanidade</strong>.',
    3: 'Acerta a si próprio com um <strong>golpe crítico</strong>, cai <strong>inconsciente</strong> por 1d6 minutos. Role na tabela <strong>Lesões Maiores</strong>',
    '4-7': 'Tropeça, torce o pé e cai, fica <strong>lento</strong> por 6 turnos (<strong>-50% movimentação</strong>).',
    '8-27': 'Torce o pé e fica <strong>lento</strong> por 5 turnos (<strong>-50% movimentação</strong>).',
    28: 'Acerta um <strong>aliado próximo</strong> com um <strong>golpe crítico</strong>.',
    29: 'Acerta a si próprio, causando o <strong>dano</strong> e <strong>atordoamento</strong> por 2 turnos.',
    30: 'Acerta um <strong>aliado próximo</strong> causando o <strong>dano normal</strong>.',
    '31-32': 'Acerta a si próprio, causando o <strong>dano</strong> e <strong>incapacitado</strong> por 1 turno.',
    '33-34': 'Acerta a si próprio, causando <strong>metade do dano</strong> e <strong>atordoamento</strong> por 1 turno.',
    '35-36': 'Acerta a si próprio, causando <strong>metade do dano</strong> e fica <strong>impedido</strong> por 1 turno.',
    '37-39': 'Acerta um <strong>aliado próximo</strong>, <strong>metade do dano</strong>.',
    40: 'A sua <strong>arma quebra</strong>. Role um d3. 1: Uma <strong>pequena parte quebra</strong>. 2: <strong>Partida ao meio</strong>. 3: Sua arma virou <strong>estilhaços, Irrecuperável</strong>.',
    '41-44': 'Algo afeta seus olhos, perde seu <strong>bônus de DES na CA</strong> e seus ataques têm <strong>50% de falha</strong> por 1d6 turnos.',
    45: 'Escorrega e fica <strong>caído</strong> no mesmo lugar. Role na Tabela <strong>Lesões Menores</strong>',
    '46-49': 'Perde a firmeza do objeto em que segura, o <strong>derruba no chão</strong>, e <strong>não pode agir</strong> no próximo turno.',
    '50-54': 'Perde a firmeza do objeto em que segura e <strong>não pode agir</strong> no próximo turno',
    '55-59': 'Perde a firmeza do objeto em que segura e o <strong>derruba no chão</strong>',
    '60-64': 'Perde o <strong>equilíbrio</strong>, mas nada acontece',
    '65-79': 'Tropeça, e fica <strong>incapacitado</strong> por 1 turno.',
    '80-99': 'Escorrega, cai, e fica <strong>incapacitado</strong> por 1 turno',
    100: 'Você é um <strong>Ser de sorte</strong>. Transforme a falha em um <strong>acerto crítico</strong>. Além disso, você ganha uma <strong>Inspiração heroica</strong>!'
};
